-- 018_seed_alt_faaliyetler.sql
-- inputs/alt_faaliyetler.csv → alt_faaliyetler + anahtar_sonuclar tabloları

BEGIN;

INSERT INTO alt_faaliyetler (sno, fkod, alt_faaliyet, anahtar_sonuclar, p_sure, tekrar_sayisi) VALUES
  (1, 'SDD601', 'SOPD:', NULL, NULL, NULL),
  (2, 'BAK601', 'BAK:', NULL, NULL, NULL),
  (3, 'ABP601', 'AB:', NULL, NULL, NULL),
  (4, 'SOG601', 'SoG:', 'SoGreen Proje görevleri tamamlandı', NULL, NULL),
  (5, 'STU101', 'Doğu Kaçkarlar Rotaları Belirlenecek', '/*Teknik Şartnamenin Hazırlanması/*Yükleniciyle Koordinasyon Toplantısı Gerçekleşirilmesi', 1, 1),
  (6, 'STU101', 'Ekoturizm Köyleri Geliştirme Yol Haritası Oluşturulacak', '/*Ekoturizm Köylerine Ziyaret Gerçekleştirildi/*Ekoturizm Köyleri Bazında Bir Çalıştay Gerçekleştirildi', 1, 1),
  (7, 'STU102', 'Hedef Pazar Analizleri Yapılacak', NULL, 1, 1),
  (8, 'STU103', 'Discover Kaçkar Markalaşma Projesi 2. Aşama', '/*Teknik Şartname Hazırlandı/*Satın Alma Evrakları Düzenlendi/*Yükleniciyle 4 Adet Koordinasyon Toplantısı Gerçekleştirildi', 1, 1),
  (9, 'STU104', 'Gümüşhane Turizm Master Planının Hazırlanması', '/*Teknik Şartname Oluşturuldu/*Yükleniciyle İlk Toplantı Gerçekleştirildi/*Satın Alma Evrakları Düzenlendi', 1, 1),
  (10, 'STU104', 'Fatsa Kabakdağı Eylem Planı Hazırlanacak', '/*Teknik Şartname Hazırlandı/*Kabakdağı''na Ziyaret Gerçekleştirildi', 1, 1),
  (11, 'STU104', 'Trabzon Turizm Master Planı Hazırlanacak', '/*Teknik Şartname Hazırlandı/*Satın Alma Evrakları Düzenlendi/*Yükleniciyle Toplantı Gerçekleştirildi', 1, 1),
  (12, 'STU201', 'GSTC Membership Alınacak', '/*GSTC Membership Başvurusu Yapıldı/*Ödeme Yapıldı', 1, 1),
  (13, 'STU201', 'UNWTO Affiliate Membership Alınacak', '/*UNWTO Affiliate Membership Başvurusu Yapıldı/*Ödeme Yapıldı', 1, 1),
  (14, 'STU201', 'Doğu Karadeniz Turizm Zirvesi Gerçekleştirildi', '/*Organizasyon Planlandı', 1, 1),
  (15, 'STU201', 'Macera Turizmi Çalıştayı Düzenlendi', '/*Organizasyon Yapıldı', 1, 1),
  (16, 'STU302', 'AdventureWEEK Katılım Sağlanacak', NULL, 1, 1),
  (17, 'STU302', 'Andora Dağ ve Macera Konferansına Katılım Sağlanacak', NULL, 1, 1),
  (18, 'STU401', '2. Dönem Kaçkar by UTMB Düzenlendi', '/*Organizasyon Gerçekleştirildi', 1, 1),
  (19, 'STU402', 'FITUR Madrid Katılım Sağlandı', '/*Organizasyon Yapıldı', 1, 1),
  (20, 'STU402', 'ITB Berlin Katılım Sağlanacak', '/*Organizasyon Yapıldı', 1, 1),
  (21, 'STU402', 'ATM Dubai Katılım Sağlandı', '/*Organizasyon Yapıldı', 1, 1),
  (22, 'STU402', 'ITB China Katılım Sağlanacak', '/*Organizasyon Gerçekleştirildi', 1, 1),
  (25, 'STU403', 'Dağ ve Macera Turizmi Temalı Fam-Tripler Düzenlenecek', '/*Teknik Şartname Hazırlandı', 1, 1),
  (26, 'STU404', 'ATM Dubai Fuarına Katılım Sağlanacak', '/*Organizasyon Yapıldı', 1, 1),
  (27, 'STU405', 'Dijital Tanıtım Filmi Hazırlanacak', '/*Teknik Şartname Hazırlandı', 1, 1),
  (28, 'STU501', 'Teknik Destek İlan Edilecek', '/*Rehber Hazırlandı/*Program İlan Edildi', 1, 1),
  (29, 'KDU103', 'Hedef pazar analizi hazırlanacak.', '/*Hedef pazar analizi sektörler seçilecek/*Hedef pazar analizi tamamlandı', 1, 1),
  (30, 'KDU108', 'Fındık Bazlı Ürünlerin Ticarileşmesine Yönelik İhtiyaç Analiz ve Eylem Planı hazırlanacak', '/*Teknik şartname hazırlandı/*Harcama oanyı alındı/*Saha planlaması yapıldı/*Başlangıç toplantısı yapıldı/*Taslak rapor hazırlandı/*Nihai Rapor hazırlandı', 1, 1),
  (31, 'KDU108', 'Doğu Karadeniz Tıbbi ve Aromatik Bitkileri 2027-2030 Eylem Planı hazırlanacak', '/*Teknik şartname hazırlandı/*Harcama onayı alındı/*Saha planlaması yapıldı/*Başlangıç toplantısı yapıldı/*Taslak rapor hazırlandı/*Nihai rapor hazırlandı', 1, 1),
  (32, 'KDU108', 'Butik Çay İhtiyaç Analizi ve Eylem Planı hazırlanacak', '/*Teknik şartname hazırlandı/*Harcama onayı alındı/*Saha planlaması yapıldı/*Başlangıç toplantısı yapıldı/*Taslak rapor hazırlandı/*Nihai rapor hazırlandı', 1, 1),
  (33, 'KDU108', 'Yerel Değer Halkası Faaliyetleri - Çarşıbaşı Keşanı hazırlandı', '/*Harcama Onayı alındı/*Rapor hazırlandı', 1, 1),
  (34, 'KDU205', 'İl yeşil dönüşüm odak grup toplantıları organize edilecek', '/*Odak grup toplantısı yapıldı', 1, 12),
  (35, 'KDU301', 'Eğitim program uygulanacak', '/*Harcama onayı alındı/*Eğitim programı uygulandı', 1, 1),
  (36, 'KDU302', 'Yalın üretim ve dijital dönüşüm konusunda iyi uygulama ziyareti gerçekleştirilecek', '/*Ziyaret planı hazırlandı/*Saha ziyareti gerçekleştirildi.', 1, 1),
  (37, 'KDU302', 'Yalın üretim ve dijital dönüşüme yönelik tecrübe paylaşımı', '/*Organizasyon hazırlıkları tamamlandı./*Organizasyon tamamlandı.', 1, 1),
  (38, 'KDU304', 'ÖZÜ ile mentörlük programı uygulanacak', '/*Program harcama onayı alındı./*Program saha uygulaması gerçekleştirildi.', 1, 1),
  (39, 'KDU305', 'Mentörlük ve Kapasite Geliştirme Programı uygulanacak', '/*Program tasarlandı/*Program uygulandı', 1, 1),
  (40, 'KDU305', 'TR90 İhracat Forumu Düzenlenecek', '/*Harcama onayı alındı/*Forum düzenlendi', 1, 1),
  (41, 'KDU406', 'Yatırım B2B Organizasyonu düzenlenecek', '/*Harcama onayı alındı/*B2B düzenlendi', 1, 1),
  (42, 'KDU407', 'Rekabetçi Sektörler KOBİ Profil Analizi Lansmanı düzenlenecek', '/*Harcama onayı alındı/*Lansman düzenlendi', 1, 1),
  (43, 'KDU501', 'Teknik Destek Programı tasarlanacak', '/*Başvuru rehberi künyesi oluşturuldu', 1, 1),
  (44, 'STU302', 'Erasus+ başvurusu hazırlanacak', '/*Proje fikri kapsamı belirlendi/*Proje ortakları belirlendi/*Proje başvuru formu hazırlandı/*Başvuru dosyası gönderildi', 5, 1),
  (45, 'STU401', 'Düzenlenen organizasyonlara destek sağlanacak', '/*Satın alma süreçleri tamamlandı', 2, 1),
  (46, 'KDU101', 'Sonuç Raporu değerlendirilecek', '/*Raporlar incelendi', 5, 1),
  (47, 'STU401', 'Etkinlik takvimi hazırlanacak', NULL, 3, 1),
  (48, 'STU401', '46 . Trabzon yarı Maratonu düzenlenecek', '/*Satın alma yapıldı', 2, 1),
  (49, 'STU104', 'Düzköy Turizm Master Planı Hazırlanması', '/*Rapor hazırlandı./*Satın alma süreçleri tamamlandı', 8, 1),
  (50, 'STU405', 'Bölge tanıtım içerikleri üretimi hizmet alımı yapılacak', '/*Teknik şartname hazırlandı/*Satın alma evrakları hazırlandı', 3, 1),
  (51, 'STU104', 'Artvin Macera Turizmi Master Plan Ön Hazırlık', '/*Rapor hazırlandı.', 2, 1),
  (52, 'STU104', 'Artvin kış turizmi fizibilitesi', '/*Rapor hazırlandı/*Satın alma süreçleri tamamlandı', 3, 1),
  (53, 'SOG601', 'Proje tanıtımı ve proje yazımına destek olundu', '/*Tanıtım yapıldı/*Proje fikri geliştirildi', 5, 1);

INSERT INTO anahtar_sonuclar (sno, as_no, anahtar_sonuc) VALUES
  (4, 1, 'SoGreen Proje görevleri tamamlandı'),
  (5, 1, 'Teknik Şartnamenin Hazırlanması'),
  (5, 2, 'Yükleniciyle Koordinasyon Toplantısı Gerçekleşirilmesi'),
  (6, 1, 'Ekoturizm Köylerine Ziyaret Gerçekleştirildi'),
  (6, 2, 'Ekoturizm Köyleri Bazında Bir Çalıştay Gerçekleştirildi'),
  (8, 1, 'Teknik Şartname Hazırlandı'),
  (8, 2, 'Satın Alma Evrakları Düzenlendi'),
  (8, 3, 'Yükleniciyle 4 Adet Koordinasyon Toplantısı Gerçekleştirildi'),
  (9, 1, 'Teknik Şartname Oluşturuldu'),
  (9, 2, 'Yükleniciyle İlk Toplantı Gerçekleştirildi'),
  (9, 3, 'Satın Alma Evrakları Düzenlendi'),
  (10, 1, 'Teknik Şartname Hazırlandı'),
  (10, 2, 'Kabakdağı''na Ziyaret Gerçekleştirildi'),
  (11, 1, 'Teknik Şartname Hazırlandı'),
  (11, 2, 'Satın Alma Evrakları Düzenlendi'),
  (11, 3, 'Yükleniciyle Toplantı Gerçekleştirildi'),
  (12, 1, 'GSTC Membership Başvurusu Yapıldı'),
  (12, 2, 'Ödeme Yapıldı'),
  (13, 1, 'UNWTO Affiliate Membership Başvurusu Yapıldı'),
  (13, 2, 'Ödeme Yapıldı'),
  (14, 1, 'Organizasyon Planlandı'),
  (15, 1, 'Organizasyon Yapıldı'),
  (18, 1, 'Organizasyon Gerçekleştirildi'),
  (19, 1, 'Organizasyon Yapıldı'),
  (20, 1, 'Organizasyon Yapıldı'),
  (21, 1, 'Organizasyon Yapıldı'),
  (22, 1, 'Organizasyon Gerçekleştirildi'),
  (25, 1, 'Teknik Şartname Hazırlandı'),
  (26, 1, 'Organizasyon Yapıldı'),
  (27, 1, 'Teknik Şartname Hazırlandı'),
  (28, 1, 'Rehber Hazırlandı'),
  (28, 2, 'Program İlan Edildi'),
  (29, 1, 'Hedef pazar analizi sektörler seçilecek'),
  (29, 2, 'Hedef pazar analizi tamamlandı'),
  (30, 1, 'Teknik şartname hazırlandı'),
  (30, 2, 'Harcama oanyı alındı'),
  (30, 3, 'Saha planlaması yapıldı'),
  (30, 4, 'Başlangıç toplantısı yapıldı'),
  (30, 5, 'Taslak rapor hazırlandı'),
  (30, 6, 'Nihai Rapor hazırlandı'),
  (31, 1, 'Teknik şartname hazırlandı'),
  (31, 2, 'Harcama onayı alındı'),
  (31, 3, 'Saha planlaması yapıldı'),
  (31, 4, 'Başlangıç toplantısı yapıldı'),
  (31, 5, 'Taslak rapor hazırlandı'),
  (31, 6, 'Nihai rapor hazırlandı'),
  (32, 1, 'Teknik şartname hazırlandı'),
  (32, 2, 'Harcama onayı alındı'),
  (32, 3, 'Saha planlaması yapıldı'),
  (32, 4, 'Başlangıç toplantısı yapıldı'),
  (32, 5, 'Taslak rapor hazırlandı'),
  (32, 6, 'Nihai rapor hazırlandı'),
  (33, 1, 'Harcama Onayı alındı'),
  (33, 2, 'Rapor hazırlandı'),
  (34, 1, 'Odak grup toplantısı yapıldı'),
  (35, 1, 'Harcama onayı alındı'),
  (35, 2, 'Eğitim programı uygulandı'),
  (36, 1, 'Ziyaret planı hazırlandı'),
  (36, 2, 'Saha ziyareti gerçekleştirildi.'),
  (37, 1, 'Organizasyon hazırlıkları tamamlandı.'),
  (37, 2, 'Organizasyon tamamlandı.'),
  (38, 1, 'Program harcama onayı alındı.'),
  (38, 2, 'Program saha uygulaması gerçekleştirildi.'),
  (39, 1, 'Program tasarlandı'),
  (39, 2, 'Program uygulandı'),
  (40, 1, 'Harcama onayı alındı'),
  (40, 2, 'Forum düzenlendi'),
  (41, 1, 'Harcama onayı alındı'),
  (41, 2, 'B2B düzenlendi'),
  (42, 1, 'Harcama onayı alındı'),
  (42, 2, 'Lansman düzenlendi'),
  (43, 1, 'Başvuru rehberi künyesi oluşturuldu'),
  (44, 1, 'Proje fikri kapsamı belirlendi'),
  (44, 2, 'Proje ortakları belirlendi'),
  (44, 3, 'Proje başvuru formu hazırlandı'),
  (44, 4, 'Başvuru dosyası gönderildi'),
  (45, 1, 'Satın alma süreçleri tamamlandı'),
  (46, 1, 'Raporlar incelendi'),
  (48, 1, 'Satın alma yapıldı'),
  (49, 1, 'Rapor hazırlandı.'),
  (49, 2, 'Satın alma süreçleri tamamlandı'),
  (50, 1, 'Teknik şartname hazırlandı'),
  (50, 2, 'Satın alma evrakları hazırlandı'),
  (51, 1, 'Rapor hazırlandı.'),
  (52, 1, 'Rapor hazırlandı'),
  (52, 2, 'Satın alma süreçleri tamamlandı'),
  (53, 1, 'Tanıtım yapıldı'),
  (53, 2, 'Proje fikri geliştirildi');

COMMIT;
